#!/bin/bash -e
if [[ "$#" -ne 1 ]]; then
    echo "Usage: build <zip-target>" 1>&2;
    exit 1;
fi;

ZIP_TARGET="$1"
export GOOS=$(echo $ZIP_TARGET | sed -E -e 's/^s3-tree-clone-([^-]+)-.*/\1/')
export ARCH=$(echo $ZIP_TARGET | sed -E -e 's/^s3-tree-clone-[^-]+-([^-]+).*/\1/')

case "$ARCH" in
    amd64 | x86_64 ) export GOARCH=amd64;;
    arm64 | aarch64 ) export GOARCH=arm64;;
    * ) export GOARCH="$ARCH";;
esac;

echo "Building s3-tree-clone-$GOOS-$ARCH"
go build -o s3-tree-clone-$GOOS-$ARCH

echo "Creating $ZIP_TARGET"
rm -rf tmp-$GOOS-$ARCH
mkdir -p tmp-$GOOS-$ARCH
cp s3-tree-clone-$GOOS-$ARCH tmp-$GOOS-$ARCH/s3-tree-clone
cd tmp-$GOOS-$ARCH
zip -9 ../${ZIP_TARGET} s3-tree-clone
rm -f s3-tree-clone
cd ..
rmdir tmp-$GOOS-$ARCH
